export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

export const SUMMITS_LOADING = 'SUMMITS_LOADING' 
export const SUMMITS_COMPLETE = 'SUMMITS_COMPLETE'
export const SUMMITS_ERROR = 'SUMMITS_ERROR'

export const SUMMIT_LOADING = 'SUMMIT_LOADING'
export const SUMMIT_COMPLETE = 'SUMMIT_COMPLETE'
export const SUMMIT_ERROR = 'SUMMIT_ERROR'

export const CLIMBERS_LOADING = 'CLIMBERS_LOADING'
export const CLIMBERS_COMPLETE = 'CLIMBERS_COMPLETE'
export const CLIMBERS_ERROR = 'CLIMBERS_ERROR'

export const SUMMIT_ADD_IMAGE = 'SUMMIT_ADD_IMAGE'
export const SUMMIT_ADD_IMAGE_SUCCESS = 'SUMMIT_ADD_IMAGE_SUCCESS'
export const SUMMIT_ADD_IMAGE_ERROR = 'SUMMIT_ADD_IMAGE_ERROR'

export const SUMMIT_DELETE_IMAGE = 'SUMMIT_DELETE_IMAGE'
export const SUMMIT_DELETE_IMAGE_SUCCESS = 'SUMMIT_DELETE_IMAGE_SUCCESS'
export const SUMMIT_DELETE_IMAGE_ERROR = 'SUMMIT_DELETE_IMAGE_ERROR'

export const SUMMIT_ADD_CLIMBER = 'SUMMIT_ADD_CLIMBER'
export const SUMMIT_ADD_CLIMBER_SUCCESS = 'SUMMIT_ADD_CLIMBER_SUCCESS'
export const SUMMIT_ADD_CLIMBER_ERROR = 'SUMMIT_ADD_CLIMBER_ERROR'

export const PROFILE_LOADING = 'PROFILE_LOADING'
// PROFILE_LOADING_SUCCESS
// PROFILE_LOADING_ERROR

export const PROFILE_SAVING = 'PROFILE_SAVING'
// PROFILE_SAVING_SUCCESS
// PROFILE_SAVING_ERROR

export const PROFILE_UPDATE_IMAGE = 'PROFILE_UPDATE_IMAGE'
// PROFILE_UPDATE_IMAGE_SUCCESS
// PROFILE_UPDATE_IMAGE_ERROR
